### ISSUE TITLE
[help] extract_info doesn't working

### ISSUE THREAD

**Issue by RocketeerFly** [pieter/YoutubeDL-iOS#2]
I tried to download video, it work perfect 👌. but no luck with "get_info" on pytest.py. This is the error traces on XCode console. I has been trying to fix this  but still stuck Please take a look at them and could you give me some advices ? Thank you in advance.

*********************************************************************************
2017-03-17 10:54:52.150 YoutubeDL[31277:75943] /Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Bundle/Application/282549F0-8817-404A-BBB0-1656827509FD/YoutubeDL.app/PythonHome
Download manager: YoutubeDL.DownloadManager
Loading preferences from /Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Data/Application/5B05AE53-833A-4C9C-A871-5265177F9FB2/Documents/playlists.plist

2017-03-17 10:54:55.692 YoutubeDL[31277:75943] Python initialized
2017-03-17 10:54:55.693 YoutubeDL[31277:75943] Going to get stream url
[youtube] DK_0jXPuIr0: Downloading webpage
2017-03-17 10:54:56.276790 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.278013 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.278867 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.279464 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.279975 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.280525 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.281075 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.281579 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.282132 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.282854 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.283405 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.283926 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.284394 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.284946 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.285509 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-03-17 10:54:56.286052 YoutubeDL[31277:75943] [] nw_host_stats_add_src recv too small, received 24, expected 28
[youtube] DK_0jXPuIr0: Downloading video info webpage
[youtube] DK_0jXPuIr0: Extracting video information
[0;33mWARNING:[0m "id" field is not a string - forcing string conversion
/Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Bundle/Application/282549F0-8817-404A-BBB0-1656827509FD/YoutubeDL.app/PythonHome/lib/python2.7/os.pyc
{u'cachedir': '/Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Data/Application/5B05AE53-833A-4C9C-A871-5265177F9FB2/Library/Caches', u'nocheckcertificate': True}
Error extracting info:
Traceback (most recent call last):
  File "/Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Bundle/Application/282549F0-8817-404A-BBB0-1656827509FD/YoutubeDL.app/PythonHome/lib/python2.7/pytest.py", line 13, in get_info
    info = ytb.extract_info(url, download=False)
  File "/Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Bundle/Application/282549F0-8817-404A-BBB0-1656827509FD/YoutubeDL.app/PythonHome/lib/python2.7/youtube_dl/YoutubeDL.py", line 772, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Bundle/Application/282549F0-8817-404A-BBB0-1656827509FD/YoutubeDL.app/PythonHome/lib/python2.7/youtube_dl/YoutubeDL.py", line 826, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Bundle/Application/282549F0-8817-404A-BBB0-1656827509FD/YoutubeDL.app/PythonHome/lib/python2.7/youtube_dl/YoutubeDL.py", line 1483, in process_video_result
    merger = FFmpegMergerPP(self)
  File "/Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Bundle/Application/282549F0-8817-404A-BBB0-1656827509FD/YoutubeDL.app/PythonHome/lib/python2.7/youtube_dl/postprocessor/ffmpeg.py", line 48, in __init__
    self._determine_executables()
  File "/Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Bundle/Application/282549F0-8817-404A-BBB0-1656827509FD/YoutubeDL.app/PythonHome/lib/python2.7/youtube_dl/postprocessor/ffmpeg.py", line 107, in _determine_executables
    (p, get_exe_version(p, args=['-version'])) for p in programs)
  File "/Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Bundle/Application/282549F0-8817-404A-BBB0-1656827509FD/YoutubeDL.app/PythonHome/lib/python2.7/youtube_dl/postprocessor/ffmpeg.py", line 107, in <genexpr>
    (p, get_exe_version(p, args=['-version'])) for p in programs)
  File "/Users/thi/Library/Developer/CoreSimulator/Devices/A1333439-6FBC-4D2F-BB2B-39EF572A6928/data/Containers/Bundle/Application/282549F0-8817-404A-BBB0-1656827509FD/YoutubeDL.app/PythonHome/lib/python2.7/youtube_dl/utils.py", line 1895, in get_exe_version
    out, _ = subprocess.Popen(
AttributeError: 'module' object has no attribute 'Popen'

*********************************************************************************

**Comment by codaman** [comment]
I am also working on this issue. I couldn't find any solution.
